@startuml
start

:User logs in;
:User interacts with TaskManager;

partition TaskManager {
    :User adds a task;
    :TaskManager stores task in allTasks;
    :User sets a reminder for the task;
    :TaskManager associates task with Reminder;
}

stop
@enduml
