@startuml Profile Management State Diagram

[*] --> ViewProfile

state ViewProfile {
    [*] --> DisplayProfileInfo
    DisplayProfileInfo --> EditProfile : Click Edit


}

state EditProfile {
    [*] --> ModifyProfileInfo
    ModifyProfileInfo --> ValidateChanges
    ValidateChanges --> SaveChanges : Valid Input
    ValidateChanges --> ModifyProfileInfo : Invalid Input
    SaveChanges --> DisplayProfileInfo : Profile Updated
}


@enduml
